# Application configuration
# 
# This file defines all configuration values for a mangoo I/O application.
# The default values are loaded by default and overwritten by environment specific
# values if they are configured.
#
# Possible environments are test and dev.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

default:
    application:
        secret: jkfhskhe7238647yh47d67t43dgh9dj3894dj
        name       : todobackend
        language   : en
        db:
            url: jdbc:h2:mem:todobackend;DB_CLOSE_DELAY=-1;
            username: sa
            password:
    connector:
        http:
            host      : localhost
            port      : 8080
    auth:
        redirect  : /login
        cookie:
            name    : todobackend-AUTH
            encrypt : false
            expires : 86400
    cookie:
        name       : todobackend-SESSION
        expires    : 86400
        encryption : false
    smtp:
        host       : localhost
        port       : 25
        username   : 
        password   : 
        ssl        : false
test:
    connector:
        http:
            host      : localhost
            port      : 9090 
    smtp:
        port       : 3025
        
dev:
    connector:
        http:
            host      : localhost
            port      : 9090 
    smtp:
        port       : 3025