routes:
# Routes configuration
#
# This file defines all application routes.
# All routes start with an identifier of the method, followed by the
# URL, followed by a mapping to the controller class and method. For
# some types a controller and method is not required.
#
# You can find a detailed explanation of the routing file in the documentation
# https://mangoo.io/docs/routing/
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- method: OPTIONS
  url: /
  mapping: ApplicationController.options

- method: OPTIONS
  url: /{id}
  mapping: ApplicationController.options

- method: GET
  url: /
  mapping: ApplicationController.getAll

- method: GET
  url: /{id}
  mapping: ApplicationController.get

- method: POST
  url: /
  mapping: ApplicationController.create

- method: DELETE
  url: /
  mapping: ApplicationController.deleteAll

- method: DELETE
  url: /{id}
  mapping: ApplicationController.delete

- method: PATCH
  url: /{id}
  mapping: ApplicationController.modify
