routes:
# Routes configuration
#
# This file defines all application routes.
# All routes start with an identifier of the method, followed by the
# URL, followed by a mapping to the controller class and method. For
# some types a controller and method is not required.
#
# You can find a detailed explanation of the routing file in the documentation
# https://mangoo.io/docs/routing/
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- method: GET
  url: /
  mapping: ApplicationController.index

- method: GET
  url: /todo
  mapping: ApplicationController.todo

- method: OPTIONS
  url: /
  mapping: ApplicationController.options
